#config file using allpix-squared built-in mesh reader tool
#to read the TCAD files for electrostatic potential
parser = "df-ise"
region = "SiliconCarbide_1"
observable = "ElectrostaticPotential"
observable_units = "V"
vector_field = False
divisions = 60, 60
