#allpix squared simulation configuration file for neutron beam and detector geometry
[AllPix]

log_level = "WARNING"
log_format = "DEFAULT"
number_of_events = 1000000
detectors_file = "/home/claire/allpix-squared/Neutrons/Neutron_detector.conf"
model_paths = "/home/claire/allpix-squared/Neutrons"

[GeometryBuilderGeant4]

world_material = "G4_AIR"

[DepositionGeant4]
physics_list = QGSP_BIC_HP
source_type = "macro"
file_name = "/home/claire/allpix-squared/Neutrons/neutron_source.mac"
source_position = 30mm 0um 0mm
max_step_length = 10.0um
number_of_particles = 1
range_cut = 1um
track_secondaries = true

[ElectricFieldReader]
model="mesh"
file_name = "/home/claire/allpix-squared/Neutrons/Meshes/PN_bias_0300_des_ElectricField.apf"
field_mapping = PIXEL_FULL
bias_voltage = 300V
output_plots = true

[GenericPropagation]
temperature = 293K
mobility_model = "constant"
# Approximate 4H-SiC room-temperature mobilities
mobility_electron = 900cm*cm/V/s
mobility_hole = 115cm*cm/V/s
charge_per_step = 100
integration_time = 200ns
propagate_electrons = true
propagate_holes = true

[SimpleTransfer]
max_depth_distance = 5um
output_plots = true

[DetectorHistogrammer]
name = "neutron_detector"
granularity = 100 100

[ROOTObjectWriter]
file_name = "Neutrons_30mm_6MeV.root"