#defines the geometry of the detector used for neutrons
type = "monolithic"
geometry = "pixel"
sensor_material = "silicon_carbide"

number_of_pixels = 1 1
pixel_size = 3mm 3mm

sensor_thickness = 53um
sensor_excess = 250um