#configuration of allpix-squared simulation for alpha beam hitting silicon carbide detector
[AllPix]

log_level = "WARNING"
log_format = "DEFAULT"
number_of_events = 1000
detectors_file = "/home/claire/allpix-squared/examples/SiC_3x3_detectorset/SiC_detector.conf"
model_paths = "/home/claire/allpix-squared/examples/SiC_3x3_detectorset"

[GeometryBuilderGeant4]

world_material = "G4_AIR"

[DepositionGeant4]
physics_list = FTFP_BERT_LIV
source_type = "macro"
file_name = "/home/claire/allpix-squared/examples/SiC_3x3_detectorset/source.mac"
source_position = 30.0um 0um 0um
max_step_length = 10.0um
number_of_particles = 1
range_cut = 10um

[ElectricFieldReader]
model="mesh"
file_name = /home/claire/allpix-squared/Neutrons/Meshes/PN_bias_0001_des_ElectricField.apf
field_mapping = PIXEL_FULL
bias_voltage = 1V
output_plots = true

[GenericPropagation]
temperature = 293K
mobility_model = "constant"
# Approximate 4H-SiC room-temperature mobilities
mobility_electron = 900cm*cm/V/s
mobility_hole = 115cm*cm/V/s
charge_per_step = 100
integration_time = 200ns
propagate_electrons = true
propagate_holes = true

[SimpleTransfer]
max_depth_distance = 5um
output_plots = true

[DetectorHistogrammer]
name = "thedetector"
granularity = 100 100

[ROOTObjectWriter]
file_name = "Am241alpha_Silicon_Carbide_30mm_1V.root"