#config file that defines the geometry of the whole 
#silicon carbide detector set up with top metal layers for alphas
[copper_top]
type = "box"
orientation_mode = "xyz"
orientation = 0deg 0deg 0deg
size = 1um 3mm 3mm
position = 1.6um 0 0
material = "copper"
role = "passive"

[aluminum_top]
type = "box"
orientation_mode = "xyz"
orientation = 0deg 0deg 0deg
size = 1um 3mm 3mm
position = 0.6um 0 0
material = "aluminum"
role = "passive"

[ti_layer]
type = "box"
orientation_mode = "xyz"
orientation = 0deg 0deg 0deg
size = 0.1um 3mm 3mm
position = 0.05um 0 0
material = "titanium"
role = "passive"

[thedetector]
type = "SiC_collimator"
orientation_mode = "xyz"
orientation = 0deg 270deg 0deg
position = -26.5um 0um 0um

[bulk_silicon]
type = "box"
size = 347um 3mm 3mm        
position = -226.5um 0 0      
material = "silicon_carbide"
orientation_mode = "xyz"
orientation = 0deg 0deg 0deg
role = "passive"

[aluminum_bottom]
type = "box"
orientation_mode = "xyz"
orientation = 0deg 0deg 0deg
size = 1um 3mm 3mm
position = -400.5um 0 0
material = "aluminum"
role = "passive"

[copper_bottom]
type = "box"
orientation_mode = "xyz"
orientation = 0deg 0deg 0deg
size = 1um 3mm 3mm
position = -401.5um 0 0
material = "copper"
role = "passive"

[pcb]
type = "box"
orientation_mode = "xyz"
orientation = 0deg 0deg 0deg
size = 1.6mm 10mm 10mm
position = -1204um 0 0
material = "g10"
role = "passive"

